disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Critical Signals"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "images/logo_cream.svg"
description = "Critical Signals explores practical and visionary responses to an era of collapses, with a focus on kai sovereignty, data sovereignty, collective resilience, and adaptation strategies under a rapidly changing climate."
